language: python


python:
  - 3.5.3
  - 3.5
  - 3.6
  - 3.7-dev
  # - 'nightly'


os:
  - linux

env:
  matrix:
    - PYTHONASYNCIODEBUG=x
    - PYTHONASYNCIODEBUG=


install:
  - pip install -U pip wheel setuptools
  - pip install -r requirements.txt
  - pip install codecov

script:
  - make cov
  - python setup.py check -rms

after_success:
  - codecov


deploy:
  provider: pypi
  user: andrew.svetlov
  password:
    secure: ZQKbdPT9BlNqP5CTbWRQyeyig7Bpf7wsnYVQIQPOZc9Ec74A+dsbagstR1sPkAO+d+5PN0pZMovvmU7OQhSVPAnJ74nsN90/fL4ux3kqYecMbevv0rJg20hMXSSkwMEIpjUsMdMjJvZAcaKytGWmKL0qAlOJHhixd1pBbWyuIUE=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    all_branches: true
    python: 3.6

