language: python


python:
  - 3.6

os:
  - linux





jobs:
  include:
    - stage test
      python:
        - 3.5.3
        - 3.5
        - 3.6
        - 3.7-dev
        # - 'nightly'
      env:
        matrix:
          - PYTHONASYNCIODEBUG=x
          - PYTHONASYNCIODEBUG=
      install:
        - pip install -U pip wheel setuptools
        - pip install -r requirements/ci.txt
        - pip install codecov
      script:
        - make cov
      after_success:
        - codecov
    - stage doc
      install:
        - pip install -r requirements/doc.txt
      script:
        - python setup.py check -rms
    - stage deploy
      install:
        - pip install -U pip wheel setuptools
      script: skip
      deploy:
        provider: pypi
        user: andrew.svetlov
        password:
          secure: ZQKbdPT9BlNqP5CTbWRQyeyig7Bpf7wsnYVQIQPOZc9Ec74A+dsbagstR1sPkAO+d+5PN0pZMovvmU7OQhSVPAnJ74nsN90/fL4ux3kqYecMbevv0rJg20hMXSSkwMEIpjUsMdMjJvZAcaKytGWmKL0qAlOJHhixd1pBbWyuIUE=
        distributions: "sdist bdist_wheel"
        on:
          tags: true
          python: 3.6
