sudo: false
language: python


python:
  - 3.5.3
  - 3.5
  - 3.6
  - 3.7-dev
  # - 'nightly'


os:
  - linux

env:
  matrix:
    - PYTHONASYNCIODEBUG=x
    - PYTHONASYNCIODEBUG=
  global:
    - STAGE=test


install:
  - pip install -U pip wheel setuptools
  - pip install -r requirements/ci.txt
  - pip install codecov

script:
  - make cov

after_success:
  - codecov


jobs:
  include:
    - stage: doc
      python: 3.6
      env:
        - STAGE=doc
      install:
        - pip install -r requirements/doc.txt
      script: 
        - python setup.py check -rms

      after_success: skip

    - stage: deploy
      python: 3.6
      env:
        - STAGE=deploy
      install: skip
      script: skip
      after_success: skip
      deploy:
        provider: pypi
        user: andrew.svetlov
        password:
          secure: ZQKbdPT9BlNqP5CTbWRQyeyig7Bpf7wsnYVQIQPOZc9Ec74A+dsbagstR1sPkAO+d+5PN0pZMovvmU7OQhSVPAnJ74nsN90/fL4ux3kqYecMbevv0rJg20hMXSSkwMEIpjUsMdMjJvZAcaKytGWmKL0qAlOJHhixd1pBbWyuIUE=
        distributions: "sdist bdist_wheel"
        on:
          tags: true
          all_branches: true
          python: 3.6
